export const officialPlan = [
    // JANEIRO (1-31) - Provérbios
    ...Array.from({ length: 31 }, (_, i) => ({
        day: i + 1,
        passage: `Provérbios ${i + 1}`,
        theme: "Sabedoria Diária",
        category: "Poéticos",
        book: "Provérbios",
        estimatedTime: "5 min"
    })),
    // FEVEREIRO (32-59) - Gênesis e Êxodo
    { day: 32, passage: "Gênesis 1-3", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 33, passage: "Gênesis 4-6", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 34, passage: "Gênesis 7-9", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 35, passage: "Gênesis 10-12", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 36, passage: "Gênesis 13-15", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 37, passage: "Gênesis 16-18", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 38, passage: "Gênesis 19-21", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 39, passage: "Gênesis 22-24", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 40, passage: "Gênesis 25-27", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 41, passage: "Gênesis 28-30", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 42, passage: "Gênesis 31-33", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 43, passage: "Gênesis 34-36", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 44, passage: "Gênesis 37-39", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 45, passage: "Gênesis 40-42", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 46, passage: "Gênesis 43-45", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 47, passage: "Gênesis 46-48", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 48, passage: "Gênesis 49-50", theme: "Princípios", category: "Pentateuco", book: "Gênesis", estimatedTime: "12 min" },
    { day: 49, passage: "Êxodo 1-4", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 50, passage: "Êxodo 5-7", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 51, passage: "Êxodo 8-10", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 52, passage: "Êxodo 11-13", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 53, passage: "Êxodo 14-16", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 54, passage: "Êxodo 17-19", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 55, passage: "Êxodo 20-22", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 56, passage: "Êxodo 23-25", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 57, passage: "Êxodo 26-28", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 58, passage: "Êxodo 29-31", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 59, passage: "Êxodo 32-34", theme: "Libertação", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    // MARÇO (60-90) - Êxodo, Levítico, Números, Deuteronômio
    { day: 60, passage: "Êxodo 35-37", theme: "O Tabernáculo", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 61, passage: "Êxodo 38-40", theme: "O Tabernáculo", category: "Pentateuco", book: "Êxodo", estimatedTime: "15 min" },
    { day: 62, passage: "Levítico 1-3", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "12 min" },
    { day: 63, passage: "Levítico 4-6", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "12 min" },
    { day: 64, passage: "Levítico 7-9", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "12 min" },
    { day: 65, passage: "Levítico 10-12", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "12 min" },
    { day: 66, passage: "Levítico 13-16", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "15 min" },
    { day: 67, passage: "Levítico 17-19", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "12 min" },
    { day: 68, passage: "Levítico 20-22", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "12 min" },
    { day: 69, passage: "Levítico 23-25", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "12 min" },
    { day: 70, passage: "Levítico 26-27", theme: "Sacrifícios", category: "Pentateuco", book: "Levítico", estimatedTime: "12 min" },
    { day: 71, passage: "Números 1-3", theme: "O Censo", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 72, passage: "Números 4-6", theme: "O Censo", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 73, passage: "Números 7-9", theme: "O Censo", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 74, passage: "Números 10-12", theme: "Caminhada", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 75, passage: "Números 13-15", theme: "Espias", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 76, passage: "Números 16-18", theme: "Rebelião", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 77, passage: "Números 19-21", theme: "Caminhada", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 78, passage: "Números 22-24", theme: "Balaão", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 79, passage: "Números 25-28", theme: "Novo Censo", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 80, passage: "Números 29-32", theme: "Leis", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 81, passage: "Números 33-36", theme: "Fronteiras", category: "Pentateuco", book: "Números", estimatedTime: "15 min" },
    { day: 82, passage: "Deuteronômio 1-3", theme: "Recordação", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    { day: 83, passage: "Deuteronômio 4-7", theme: "A Lei", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    { day: 84, passage: "Deuteronômio 8-11", theme: "Advertências", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    { day: 85, passage: "Deuteronômio 12-15", theme: "Leis", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    { day: 86, passage: "Deuteronômio 16-19", theme: "Festas", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    { day: 87, passage: "Deuteronômio 20-23", theme: "Guerra e Leis", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    { day: 88, passage: "Deuteronômio 24-27", theme: "Obediência", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    { day: 89, passage: "Deuteronômio 28-31", theme: "Bênçãos e Maldições", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    { day: 90, passage: "Deuteronômio 32-34", theme: "Morte de Moisés", category: "Pentateuco", book: "Deuteronômio", estimatedTime: "15 min" },
    // ABRIL (91-120) - Salmos
    ...[
        "1-5", "6-10", "11-15", "16-20", "21-26", "27-32", "33-37", "38-41", "42-46", "47-50",
        "51-55", "56-60", "61-65", "66-68", "69-72", "73-76", "77-79", "80-85", "86-89", "90-94",
        "95-101", "102-104", "105-107", "108-113", "114-118", "119", "120-128", "129-136", "137-143", "144-150"
    ].map((p, i) => ({
        day: 91 + i,
        passage: `Salmos ${p}`,
        theme: "Adoração e Oração",
        category: "Poéticos",
        book: "Salmos",
        estimatedTime: "10 min"
    })),
    // MAIO (121-151) - Josué, Juízes, Rute, 1 Samuel, 2 Samuel
    ...Array.from({ length: 8 }, (_, i) => ({
        day: 121 + i,
        passage: `Josué ${i * 3 + 1}-${Math.min((i + 1) * 3, 24)}`,
        theme: "Conquista",
        category: "Históricos",
        book: "Josué",
        estimatedTime: "15 min"
    })),
    ...Array.from({ length: 7 }, (_, i) => ({
        day: 129 + i,
        passage: `Juízes ${i * 3 + 1}-${Math.min((i + 1) * 3, 21)}`,
        theme: "Os Juízes",
        category: "Históricos",
        book: "Juízes",
        estimatedTime: "15 min"
    })),
    { day: 136, passage: "Rute 1-4", theme: "Lealdade", category: "Históricos", book: "Rute", estimatedTime: "12 min" },
    { day: 137, passage: "1 Samuel 1-3", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 138, passage: "1 Samuel 4-6", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 139, passage: "1 Samuel 7-9", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 140, passage: "1 Samuel 10-12", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 141, passage: "1 Samuel 13-15", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 142, passage: "1 Samuel 16-18", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 143, passage: "1 Samuel 19-21", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 144, passage: "1 Samuel 22-24", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 145, passage: "1 Samuel 25-27", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 146, passage: "1 Samuel 28-31", theme: "Reinado", category: "Históricos", book: "1 Samuel", estimatedTime: "15 min" },
    { day: 147, passage: "2 Samuel 1-3", theme: "Davi Rei", category: "Históricos", book: "2 Samuel", estimatedTime: "15 min" },
    { day: 148, passage: "2 Samuel 4-6", theme: "Davi Rei", category: "Históricos", book: "2 Samuel", estimatedTime: "15 min" },
    { day: 149, passage: "2 Samuel 7-9", theme: "Davi Rei", category: "Históricos", book: "2 Samuel", estimatedTime: "15 min" },
    { day: 150, passage: "2 Samuel 10-12", theme: "Davi Rei", category: "Históricos", book: "2 Samuel", estimatedTime: "15 min" },
    { day: 151, passage: "2 Samuel 13-15", theme: "Davi Rei", category: "Históricos", book: "2 Samuel", estimatedTime: "15 min" },
    // JUNHO (152-181) - 2 Samuel, Reis, Crônicas
    { day: 152, passage: "2 Samuel 16-18", theme: "Reinado", category: "Históricos", book: "2 Samuel", estimatedTime: "15 min" },
    { day: 153, passage: "2 Samuel 19-21", theme: "Reinado", category: "Históricos", book: "2 Samuel", estimatedTime: "15 min" },
    { day: 154, passage: "2 Samuel 22-24", theme: "Reinado", category: "Históricos", book: "2 Samuel", estimatedTime: "15 min" },
    { day: 155, passage: "1 Reis 1-3", theme: "Reis de Israel", category: "Históricos", book: "1 Reis", estimatedTime: "15 min" },
    { day: 156, passage: "1 Reis 4-6", theme: "Reis de Israel", category: "Históricos", book: "1 Reis", estimatedTime: "15 min" },
    { day: 157, passage: "1 Reis 7-9", theme: "Reis de Israel", category: "Históricos", book: "1 Reis", estimatedTime: "15 min" },
    { day: 158, passage: "1 Reis 10-12", theme: "Reis de Israel", category: "Históricos", book: "1 Reis", estimatedTime: "15 min" },
    { day: 159, passage: "1 Reis 13-15", theme: "Reis de Israel", category: "Históricos", book: "1 Reis", estimatedTime: "15 min" },
    { day: 160, passage: "1 Reis 16-18", theme: "Reis de Israel", category: "Históricos", book: "1 Reis", estimatedTime: "15 min" },
    { day: 161, passage: "1 Reis 19-22", theme: "Reis de Israel", category: "Históricos", book: "1 Reis", estimatedTime: "15 min" },
    { day: 162, passage: "2 Reis 1-3", theme: "Profetas e Reis", category: "Históricos", book: "2 Reis", estimatedTime: "15 min" },
    { day: 163, passage: "2 Reis 4-6", theme: "Profetas e Reis", category: "Históricos", book: "2 Reis", estimatedTime: "15 min" },
    { day: 164, passage: "2 Reis 7-9", theme: "Profetas e Reis", category: "Históricos", book: "2 Reis", estimatedTime: "15 min" },
    { day: 165, passage: "2 Reis 10-12", theme: "Profetas e Reis", category: "Históricos", book: "2 Reis", estimatedTime: "15 min" },
    { day: 166, passage: "2 Reis 13-15", theme: "Profetas e Reis", category: "Históricos", book: "2 Reis", estimatedTime: "15 min" },
    { day: 167, passage: "2 Reis 16-18", theme: "Profetas e Reis", category: "Históricos", book: "2 Reis", estimatedTime: "15 min" },
    { day: 168, passage: "2 Reis 19-21", theme: "Profetas e Reis", category: "Históricos", book: "2 Reis", estimatedTime: "15 min" },
    { day: 169, passage: "2 Reis 22-25", theme: "Profetas e Reis", category: "Históricos", book: "2 Reis", estimatedTime: "15 min" },
    { day: 170, passage: "1 Crônicas 1-3", theme: "Genealogia", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 171, passage: "1 Crônicas 4-6", theme: "Genealogia", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 172, passage: "1 Crônicas 7-9", theme: "Genealogia", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 173, passage: "1 Crônicas 10-12", theme: "Reinado de Davi", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 174, passage: "1 Crônicas 13-15", theme: "A Arca", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 175, passage: "1 Crônicas 16-18", theme: "Sucesso", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 176, passage: "1 Crônicas 19-21", theme: "Militar", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 177, passage: "1 Crônicas 22-24", theme: "O Templo", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 178, passage: "1 Crônicas 25-27", theme: "Organização", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 179, passage: "1 Crônicas 28-29", theme: "Morte de Davi", category: "Históricos", book: "1 Crônicas", estimatedTime: "15 min" },
    { day: 180, passage: "2 Crônicas 1-3", theme: "Salomão", category: "Históricos", book: "2 Crônicas", estimatedTime: "15 min" },
    { day: 181, passage: "2 Crônicas 4-6", theme: "O Templo", category: "Históricos", book: "2 Crônicas", estimatedTime: "15 min" },
    // JULHO (182-212) - Crônicas, Esdras, Neemias, Ester, Jó
    ...Array.from({ length: 10 }, (_, i) => ({
        day: 182 + i,
        passage: `2 Crônicas ${i * 3 + 7}-${Math.min(i * 3 + 9, 36)}`,
        theme: "História de Judá",
        category: "Históricos",
        book: "2 Crônicas",
        estimatedTime: "15 min"
    })),
    { day: 192, passage: "Esdras 1-3", theme: "O Retorno", category: "Históricos", book: "Esdras", estimatedTime: "12 min" },
    { day: 193, passage: "Esdras 4-6", theme: "Reconstrução", category: "Históricos", book: "Esdras", estimatedTime: "12 min" },
    { day: 194, passage: "Esdras 7-10", theme: "Lei de Deus", category: "Históricos", book: "Esdras", estimatedTime: "15 min" },
    { day: 195, passage: "Neemias 1-3", theme: "Os Muros", category: "Históricos", book: "Neemias", estimatedTime: "12 min" },
    { day: 196, passage: "Neemias 4-6", theme: "Oposição", category: "Históricos", book: "Neemias", estimatedTime: "12 min" },
    { day: 197, passage: "Neemias 7-10", theme: "Renovação", category: "Históricos", book: "Neemias", estimatedTime: "15 min" },
    { day: 198, passage: "Neemias 11-13", theme: "Dedicação", category: "Históricos", book: "Neemias", estimatedTime: "12 min" },
    { day: 199, passage: "Ester 1-3", theme: "Providência", category: "Históricos", book: "Ester", estimatedTime: "12 min" },
    { day: 200, passage: "Ester 4-6", theme: "Coragem", category: "Históricos", book: "Ester", estimatedTime: "12 min" },
    { day: 201, passage: "Ester 7-10", theme: "Livramento", category: "Históricos", book: "Ester", estimatedTime: "12 min" },
    ...Array.from({ length: 11 }, (_, i) => ({
        day: 202 + i,
        passage: `Jó ${i * 4 + 1}-${Math.min(i * 4 + 4, 42)}`,
        theme: "Sofrimento e Fé",
        category: "Poéticos",
        book: "Jó",
        estimatedTime: "15 min"
    })).map(d => d.day === 211 ? { ...d, passage: "Jó 37-39" } : d.day === 212 ? { ...d, passage: "Jó 40-42" } : d),
    // AGOSTO (213-243) - Eclesiastes, Cantares, Isaías, Jeremias
    { day: 213, passage: "Eclesiastes 1-3", theme: "Vaidade", category: "Poéticos", book: "Eclesiastes", estimatedTime: "10 min" },
    { day: 214, passage: "Eclesiastes 4-6", theme: "Vaidade", category: "Poéticos", book: "Eclesiastes", estimatedTime: "10 min" },
    { day: 215, passage: "Eclesiastes 7-9", theme: "Vaidade", category: "Poéticos", book: "Eclesiastes", estimatedTime: "10 min" },
    { day: 216, passage: "Eclesiastes 10-12", theme: "Conclusão", category: "Poéticos", book: "Eclesiastes", estimatedTime: "10 min" },
    { day: 217, passage: "Cantares 1-3", theme: "Amor", category: "Poéticos", book: "Cantares", estimatedTime: "10 min" },
    { day: 218, passage: "Cantares 4-6", theme: "Amor", category: "Poéticos", book: "Cantares", estimatedTime: "10 min" },
    { day: 219, passage: "Cantares 7-8", theme: "Amor", category: "Poéticos", book: "Cantares", estimatedTime: "10 min" },
    ...Array.from({ length: 16 }, (_, i) => ({
        day: 220 + i,
        passage: `Isaías ${i * 4 + 1}-${Math.min(i * 4 + 4, 66)}`,
        theme: "Profecia",
        category: "Profetas Maiores",
        book: "Isaías",
        estimatedTime: "15 min"
    })).map(d => d.day === 234 ? { ...d, passage: "Isaías 57-61" } : d.day === 235 ? { ...d, passage: "Isaías 62-66" } : d),
    ...Array.from({ length: 8 }, (_, i) => ({
        day: 236 + i,
        passage: `Jeremias ${i * 4 + 1}-${i * 4 + 4}`,
        theme: "O Profeta",
        category: "Profetas Maiores",
        book: "Jeremias",
        estimatedTime: "15 min"
    })),
    // SETEMBRO (244-273) - Jeremias, Lamentações, Ezequiel, Daniel, Oséias, Joel, Amós
    ...Array.from({ length: 5 }, (_, i) => ({
        day: 244 + i,
        passage: `Jeremias ${i * 4 + 33}-${i * 4 + 36}`,
        theme: "Julgamento",
        category: "Profetas Maiores",
        book: "Jeremias",
        estimatedTime: "15 min"
    })),
    { day: 249, passage: "Lamentações 1-5", theme: "Tristeza", category: "Profetas Maiores", book: "Lamentações", estimatedTime: "15 min" },
    ...Array.from({ length: 12 }, (_, i) => ({
        day: 250 + i,
        passage: `Ezequiel ${i * 4 + 1}-${i * 4 + 4}`,
        theme: "Visões",
        category: "Profetas Maiores",
        book: "Ezequiel",
        estimatedTime: "15 min"
    })),
    ...Array.from({ length: 4 }, (_, i) => ({
        day: 262 + i,
        passage: `Daniel ${i * 3 + 1}-${i * 3 + 3}`,
        theme: "Profecia",
        category: "Profetas Maiores",
        book: "Daniel",
        estimatedTime: "12 min"
    })),
    ...Array.from({ length: 4 }, (_, i) => ({
        day: 266 + i,
        passage: `Oséias ${i * 3 + 1}-${Math.min(i * 3 + 3, 14)}`,
        theme: "Amor de Deus",
        category: "Profetas Menores",
        book: "Oséias",
        estimatedTime: "12 min"
    })).map(d => d.day === 269 ? { ...d, passage: "Oséias 10-14" } : d),
    { day: 270, passage: "Joel 1-3", theme: "O Dia do Senhor", category: "Profetas Menores", book: "Joel", estimatedTime: "10 min" },
    { day: 271, passage: "Amós 1-3", theme: "Justiça", category: "Profetas Menores", book: "Amós", estimatedTime: "12 min" },
    { day: 272, passage: "Amós 4-6", theme: "Justiça", category: "Profetas Menores", book: "Amós", estimatedTime: "12 min" },
    { day: 273, passage: "Amós 7-9", theme: "Justiça", category: "Profetas Menores", book: "Amós", estimatedTime: "12 min" },
    // OUTUBRO (274-304) - Profetas Menores e NT (Mateus, Marcos, Lucas)
    { day: 274, passage: "Obadias 1 / Jonas 1-4", theme: "Julgamento e Misericórdia", category: "Profetas Menores", book: "Vários", estimatedTime: "15 min" },
    { day: 275, passage: "Miquéias 1-4", theme: "Justiça", category: "Profetas Menores", book: "Miquéias", estimatedTime: "12 min" },
    { day: 276, passage: "Miquéias 5-7", theme: "Esperança", category: "Profetas Menores", book: "Miquéias", estimatedTime: "10 min" },
    { day: 277, passage: "Naum 1-3", theme: "Julgamento", category: "Profetas Menores", book: "Naum", estimatedTime: "10 min" },
    { day: 278, passage: "Habacuque 1-3", theme: "Fé", category: "Profetas Menores", book: "Habacuque", estimatedTime: "10 min" },
    { day: 279, passage: "Sofonias 1-3", theme: "Julgamento", category: "Profetas Menores", book: "Sofonias", estimatedTime: "10 min" },
    { day: 280, passage: "Ageu 1-2", theme: "Reconstrução", category: "Profetas Menores", book: "Ageu", estimatedTime: "10 min" },
    ...Array.from({ length: 4 }, (_, i) => ({
        day: 281 + i,
        passage: `Zacarias ${i * 3 + 1}-${Math.min(i * 3 + 3, 14)}`,
        theme: "Restauração",
        category: "Profetas Menores",
        book: "Zacarias",
        estimatedTime: "12 min"
    })).map(d => d.day === 284 ? { ...d, passage: "Zacarias 11-14" } : d),
    { day: 285, passage: "Malaquias 1-4", theme: "Advertência", category: "Profetas Menores", book: "Malaquias", estimatedTime: "10 min" },
    ...Array.from({ length: 9 }, (_, i) => ({
        day: 286 + i,
        passage: `Mateus ${i * 3 + 1}-${Math.min(i * 3 + 3, 28)}`,
        theme: "O Rei",
        category: "Evangelhos",
        book: "Mateus",
        estimatedTime: "15 min"
    })).map(d => d.day === 294 ? { ...d, passage: "Mateus 26-28" } : d),
    ...Array.from({ length: 5 }, (_, i) => ({
        day: 295 + i,
        passage: `Marcos ${i * 3 + 1}-${Math.min(i * 3 + 3, 16)}`,
        theme: "O Servo",
        category: "Evangelhos",
        book: "Marcos",
        estimatedTime: "15 min"
    })).map(d => d.day === 299 ? { ...d, passage: "Marcos 14-16" } : d),
    ...Array.from({ length: 5 }, (_, i) => ({
        day: 300 + i,
        passage: `Lucas ${i * 3 + 1}-${Math.min(i * 3 + 3, 15)}`,
        theme: "O Filho do Homem",
        category: "Evangelhos",
        book: "Lucas",
        estimatedTime: "15 min"
    })),
    // NOVEMBRO (305-334) - Lucas, João, Atos, Romanos, 1 Coríntios, 2 Coríntios
    ...Array.from({ length: 3 }, (_, i) => ({
        day: 305 + i,
        passage: `Lucas ${i * 3 + 16}-${Math.min(i * 3 + 18, 24)}`,
        theme: "O Salvador",
        category: "Evangelhos",
        book: "Lucas",
        estimatedTime: "15 min"
    })).map(d => d.day === 307 ? { ...d, passage: "Lucas 22-24" } : d),
    ...Array.from({ length: 7 }, (_, i) => ({
        day: 308 + i,
        passage: `João ${i * 3 + 1}-${Math.min(i * 3 + 3, 21)}`,
        theme: "O Filho de Deus",
        category: "Evangelhos",
        book: "João",
        estimatedTime: "15 min"
    })),
    ...Array.from({ length: 9 }, (_, i) => ({
        day: 315 + i,
        passage: `Atos ${i * 3 + 1}-${Math.min(i * 3 + 3, 28)}`,
        theme: "A Igreja",
        category: "Históricos NT",
        book: "Atos",
        estimatedTime: "15 min"
    })).map(d => d.day === 323 ? { ...d, passage: "Atos 26-28" } : d),
    ...Array.from({ length: 5 }, (_, i) => ({
        day: 324 + i,
        passage: `Romanos ${i * 3 + 1}-${Math.min(i * 3 + 3, 16)}`,
        theme: "Justiça pela Fé",
        category: "Epístolas",
        book: "Romanos",
        estimatedTime: "15 min"
    })).map(d => d.day === 325 ? { ...d, passage: "Romanos 4-7" } : d.day === 328 ? { ...d, passage: "Romanos 14-16" } : d),
    ...Array.from({ length: 5 }, (_, i) => ({
        day: 329 + i,
        passage: `1 Coríntios ${i * 3 + 1}-${Math.min(i * 3 + 3, 16)}`,
        theme: "Vida na Igreja",
        category: "Epístolas",
        book: "1 Coríntios",
        estimatedTime: "15 min"
    })).map(d => d.day === 333 ? { ...d, passage: "1 Coríntios 14-16" } : d),
    { day: 334, passage: "2 Coríntios 1-4", theme: "Consolo", category: "Epístolas", book: "2 Coríntios", estimatedTime: "15 min" },
    // DEZEMBRO (335-365) - 2 Coríntios, Gálatas, Efésios, ... Apocalipse
    { day: 335, passage: "2 Coríntios 5-7", theme: "Consolo", category: "Epístolas", book: "2 Coríntios", estimatedTime: "12 min" },
    { day: 336, passage: "2 Coríntios 8-10", theme: "Consolo", category: "Epístolas", book: "2 Coríntios", estimatedTime: "12 min" },
    { day: 337, passage: "2 Coríntios 11-13", theme: "Consolo", category: "Epístolas", book: "2 Coríntios", estimatedTime: "12 min" },
    { day: 338, passage: "Gálatas 1-3", theme: "Liberdade", category: "Epístolas", book: "Gálatas", estimatedTime: "12 min" },
    { day: 339, passage: "Gálatas 4-6", theme: "Liberdade", category: "Epístolas", book: "Gálatas", estimatedTime: "12 min" },
    { day: 340, passage: "Efésios 1-3", theme: "A Igreja", category: "Epístolas", book: "Efésios", estimatedTime: "12 min" },
    { day: 341, passage: "Efésios 4-6", theme: "A Igreja", category: "Epístolas", book: "Efésios", estimatedTime: "12 min" },
    { day: 342, passage: "Filipenses 1-4", theme: "Alegria", category: "Epístolas", book: "Filipenses", estimatedTime: "15 min" },
    { day: 343, passage: "Colossenses 1-4", theme: "Cristo", category: "Epístolas", book: "Colossenses", estimatedTime: "15 min" },
    { day: 344, passage: "1 Tessalonicenses 1-5", theme: "Esperança", category: "Epístolas", book: "1 Tessalonicenses", estimatedTime: "15 min" },
    { day: 345, passage: "2 Tessalonicenses 1-3", theme: "O Fim", category: "Epístolas", book: "2 Tessalonicenses", estimatedTime: "12 min" },
    { day: 346, passage: "1 Timóteo 1-3", theme: "Manual Pastoral", category: "Epístolas", book: "1 Timóteo", estimatedTime: "12 min" },
    { day: 347, passage: "1 Timóteo 4-6", theme: "Manual Pastoral", category: "Epístolas", book: "1 Timóteo", estimatedTime: "12 min" },
    { day: 348, passage: "2 Timóteo 1-4", theme: "O Bom Combate", category: "Epístolas", book: "2 Timóteo", estimatedTime: "15 min" },
    { day: 349, passage: "Tito 1-3 / Filemom 1", theme: "Conselhos", category: "Epístolas", book: "Vários", estimatedTime: "15 min" },
    { day: 350, passage: "Hebreus 1-4", theme: "Superioridade", category: "Epístolas", book: "Hebreus", estimatedTime: "15 min" },
    { day: 351, passage: "Hebreus 5-7", theme: "Superioridade", category: "Epístolas", book: "Hebreus", estimatedTime: "15 min" },
    { day: 352, passage: "Hebreus 8-10", theme: "Superioridade", category: "Epístolas", book: "Hebreus", estimatedTime: "15 min" },
    { day: 353, passage: "Hebreus 11-13", theme: "Superioridade", category: "Epístolas", book: "Hebreus", estimatedTime: "15 min" },
    { day: 354, passage: "Tiago 1-5", theme: "Fé e Obras", category: "Epístolas", book: "Tiago", estimatedTime: "15 min" },
    { day: 355, passage: "1 Pedro 1-5", theme: "Sofrimento", category: "Epístolas", book: "1 Pedro", estimatedTime: "15 min" },
    { day: 356, passage: "2 Pedro 1-3", theme: "Conhecimento", category: "Epístolas", book: "2 Pedro", estimatedTime: "12 min" },
    { day: 357, passage: "1 João 1-5", theme: "Amor", category: "Epístolas", book: "1 João", estimatedTime: "15 min" },
    { day: 358, passage: "2 e 3 João / Judas", theme: "Verdade", category: "Epístolas", book: "Vários", estimatedTime: "12 min" },
    ...Array.from({ length: 7 }, (_, i) => ({
        day: 359 + i,
        passage: `Apocalipse ${["1-3", "4-6", "7-9", "10-12", "13-15", "16-18", "19-22"][i]}`,
        theme: "A Revelação",
        category: "Revelação",
        book: "Apocalipse",
        estimatedTime: "15 min"
    }))
];
